# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

Vagrant.configure("2") do |config|

    config.vm.define "elk01" do |subconfig|
      subconfig.vm.box = "debian/stretch64"
      subconfig.vm.hostname = "elk01"
      subconfig.vm.network :private_network, ip: "192.168.121.17"
      #subconfig.vm.network :forwarded_port, guest: 80, host: 8080
      subconfig.vm.provision "shell", path: "elk.sh"
      #subconfig.vm.provision "shell", path: "prometheus/node_exporter.sh"
      #subconfig.vm.provision "ansible" do |ansible|
      #    ansible.playbook = "webserver/webserver.yml"
      #end
      subconfig.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 1
      end
    end
end