---
- name: NGINX | Install and configure NGINX
  hosts: webserver01
  become: true
  vars:
    nginx_listen_port: 80

  tasks:
    - name: NGINX | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL Repo
      yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: NGINX | Create NGINX config files from template
      copy:
        src: "templates/upstream.conf"
        dest: "/etc/nginx/conf.d/upstream.conf"

    - name: NGINX | Create NGINX config files from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

- name: APACHE | Install and configure APACHE
  hosts: webserver01
  become: true
  
  tasks:
    - name: APACHE | Install APACHE package
      yum:
        name: httpd
        state: latest
      notify:
        - restart httpd
      tags:
        - httpd-package
        - packages

    - name: APACHE | Create APACHE config files from template
      copy:
        src: "templates/upstream.conf"
        dest: "/etc/nginx/conf.d/upstream.conf"

    - name: NGINX | Create NGINX config files from template
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'templates/httpd/conf.d/', dest: '/etc/httpd/conf.d/' }
        - { src: 'templates/httpd/conf/httpd.conf', dest: '/etc/httpd/conf/httpd.conf' }
        - { src: 'templates/httpd/www/', dest: '/var/www/' }
      notify:
        - reload httpd
      tags:
        - httpd-configuration

  handlers:
    - name: restart httpd
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    
    - name: reload httpd
      systemd:
        name: httpd
        state: reloaded