Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.ssh.forward_agent = true
  
    #config.vm.network "forwarded_port", guest: 9200, host: 9200
    #config.vm.network "forwarded_port", guest: 9292, host: 9292
    #config.vm.network "forwarded_port", guest: 5601, host: 5601
  end