# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "centos/7"

Vagrant.configure("2") do |config|
 
  config.vm.define "prometheus01" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "prometheus01"
    subconfig.vm.network :private_network, ip: "192.168.121.14"
    subconfig.vm.network :forwarded_port, guest: 9090, host: 9090
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
    config.vm.provision "shell", path: "prometheus/prometheus.sh"
  end

end