# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "centos/7"
Vagrant.configure("2") do |config|
    config.vm.define "mysql01" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "mysql01"
        subconfig.vm.network :private_network, ip: "192.168.121.12"
        config.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
          end
        end
    
      config.vm.define "mysql02" do |subconfig| 
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "mysql02"
        subconfig.vm.network :private_network, ip: "192.168.121.13"
        config.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
          end
      end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "install_sqlserver.yml"
    end
end