---
- name: Trying to do something with Mysql
  hosts: sql
  #become: true
  vars:
  #  nginx_listen_port: 8080
  #  ansible_hostname: localhost

    #mysql_root_password: AstraAstra1#
  
  tasks: 
    - name: test mysql_secure_installation
      mysql_secure_installation:
        login_password: ''
        new_password: password22
        user: root
        login_host: localhost
        hosts: ['localhost', '127.0.0.1', '::1']
        change_root_password: true
        remove_anonymous_user: true
        disallow_root_login_remotely: true
        remove_test_db: true
        #register: mysql_secure

# To see detailed output
#    - debug:
#        var: mysql_secure
...