---
- name: Trying to do something with Mysql
  hosts: sql
  become: true
  vars:
  #  nginx_listen_port: 8080
  #  ansible_hostname: localhost

    #mysql_root_password: AstraAstra1#
  
  tasks: 
    - name: Run the command if the specified file does not exist.
      shell: /vagrant/extract_bd_passwd.sh

...