---
- name: Install MySQL on both VM
  hosts: all
  become: true
  vars:
    nginx_listen_port: 8080
  
  tasks: 
    - name: Install wget
      yum:
        name: wget
        state: present
    
    - name: Download the MySql
      get_url:
        url: http://repo.mysql.com/mysql80-community-release-el7.rpm
        dest: ~/
        mode: 0440
    - name:
      shell: rpm -i mysql80-community-release-el7.rpm
    - name:
      shell: yum repolist enabled | grep "mysql.*-community.*"
    - name:
      yum:
        name: mysql-community-server.x86_64
        state: present
      
...